### ISSUE TITLE
Problen in installation

### ISSUE THREAD

**Issue by rafaelreis2** [guidov/pygamman#4]
Hi I'm having a problem with the installation
python setup.py install
Egg name: pygamman-0.1.egg-info
running install
running build
running build_py
Traceback (most recent call last):
  File "setup.py", line 120, in <module>
    'Programming Language :: Python :: >2.6']
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 43, in run
    build.run(self)
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/build_py.py", line 9, in run
    build_src = self.get_finalized_command('build_src')
  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/build_src.py", line 128, in finalize_options
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/build_ext.py", line 75, in finalize_options
    self.set_undefined_options('build', ('parallel', 'parallel'))
  File "/usr/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
    getattr(src_cmd_obj, src_option))
  File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: parallel

**Comment by AdrianoGiangiardi** [comment]
I am also have same problem, do you get install?

**Comment by guidov** [comment]
Hi ,
Sorry, I'm no longer maintaining this repository.

Have a look at this github discussion it may help

https://github.com/TEOS-10/GSW-Python/issues/52
